### PR TITLE
Don't stop validation after first invalid field found

### PR DESCRIPTION
**Pull request by yasuyuki-baba**
Sometimes, I don't want to stop the validation after found first invalid field.
Would you merge my changes?

### CODE REVIEW

**Comment by jirutka** [comment]
Good idea, could you please add some tests for the new behaviour?

**Comment by yasuyuki-baba** [comment]
Hi, I added tests.

**Comment by ncsibra** [comment]
Hi,

Is there any reason why it's not merged?
I would love to see this feature, but maybe the `stopAfterFoundFirstInvalidField` name is a little bit too verbose, `failFast` would be better.
Actually Hibernate Validator use the same wording, see [Fail fast mode](https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/?v=5.4#section-fail-fast)

**Comment by yasuyuki-baba** [comment]
Hi @ncsibra 
Thank you your suggestion. I changed it to `failFast`

@jirutka How about?

**Comment by filipowm** [comment]
Hi @jirutka 
Any update? It would be really nice to have this feature.

**Comment by FilipMalczak** [comment]
+1. I'm here to make this thread alive, since I find the feature useful.

**Comment by sarxos** [comment]
Hi @jirutka, can we have this merged please?

**Comment by mxw589** [comment]
Hi @jirutka also would love to have this feature

**Comment by yasuyuki-baba** [comment]
No longer needed this PR.
I close it.

**Pull request closed without merging**
